title: John hirleman
email: hire.johnhirleman@gmail.com
description: >-
  A portfolio of my projects and past work experience.
baseurl: "my-portfolio"
url: "https://johnhirleman.github.io"
github_username:  johnhirleman

# Build settings
#theme: minima
plugins:
  - jekyll-feed

# Collections for projects
collections:
  projects:
    output: true
    permalink: /projects/:name/

#sass
sass:
  sass_dir: _sass
  style: compressed

#skills data
skills:
  languages:
    - HTML
    - CSS
    - JavaScript
    - Liquid
  frameworks:
    - Node.js
    - React
    - Angular
  tools:
    - Git
  editors:
    - VS Code
    - Sublime Text
  software:
    - Figma
    - Framer
    - Adobe Creative Suite
    - Adobe XD
    - Sketch
  applied skills:
    - UX/UI Design
    - Responsive Design
    - User Research
    - Prototyping
    - Wireframing
    - Front-end Development
    - A/B Testing
    - Communication
    - Teamwork
    - Problem-solving
    - Agile/Scrum

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
